# Whale you be my container?
#
# VERSION       0.42

# use the base image provided by Docker
FROM ubuntu:12.04

MAINTAINER Moby Dock victor.coisne@docker.com

# say hello when the container is launched
CMD echo "Whale you be my container"
